### ISSUE TITLE
Konfiguration für lokales Backend (Abgabe)

### ISSUE THREAD

**Issue by daullmer** [Cryp-Tour/website#40]
Für die Abgabe, muss das gesamte Projekt lokal ausgeführt werden können (glaube ich?; und natürlich ohne Blockchain). Aktuell ist es aber nicht möglich, den Live-API-Endpunkt `backend.cryptour.dullmer.de` durch `localhost:3030` zu ersetzen.
Ich sehe aktuell folgende Möglichkeiten, wie man das Frontend auch gegen ein lokales Backend ausführen kann:

1. Projekt zu [Webpack](https://github.com/webpack/webpack) (oder ähnliches) migrieren, dass während dem Bundle-Vorgang, die URL ersetzt. Ich persönlich habe aber keine Ahnung wie das geht
2. Node/Python/Bash Skript, welches mit `sed` (oder ähnlichem) alle URLs automatisch ersetzt
3. In der Installationsanleitung schreiben in welchen Dateien man die URL durch Localhost ersetzen muss (worst case Lösung)
4. @fabiankuffer hast du vielleicht noch eine Idee?

**Comment by fabiankuffer** [comment]
Wir sollten ihn am besten noch einmal fragen, ob es wirklich lokal laufen muss.
Ich weiß nämlich nicht ob mit den Session-Cookies auch auf ein lokaler Server funktioniert, da ich meistens immer die Fehlermeldungen unter Chrome bekommen hab, dass die Verbindung dann mit https sein muss. Postman sollte aber funktionieren, da dort keine CORS-Policy hinterlegt ist.
Das mit sed klingt machbar. Man könnte aber auch eine externe js Datei erstellen in der eine globale Variable gesetzt ist mit der Base-URL. Die js-Datei müsste, dann bei jeder html-Seite vor allen js-Skripts importiert werden und dann müssten alle URLs so angepasst werden, dass diese die globale Variable verwenden.

**Comment by fabiankuffer** [comment]
Ich hab jetzt für das Issue ein Branch erstellt in dem die BaseURL in der config.js gesetzt wird. Es funktioniert auch, dass die Repos Website und Server lokal ausgeführt werden ohne CORS Probleme.

Wenn es @daullmer so passt kannst du eigentlich den Branch mergen, sollte hoffentlich dann noch alles funktionieren :sweat_smile:

**Comment by daullmer** [comment]
Wenn es funktioniert hab ich kein Problem das zu mergen 👌🏻
