### ISSUE TITLE
Tour-Details: Bildergalerie

### ISSUE THREAD

**Issue by fabiankuffer** [Cryp-Tour/website#41]
Reicht die Bildergalerie nicht schon wie sie jetzt ist?

**Comment by daullmer** [comment]
Wenn beim Erstellen die Bilder weiter auf 3 limitiert sind, passt es für mich so

**Comment by fabiankuffer** [comment]
Ich hab es so gemacht, dass nur die Tour erstellt werden kann, wenn genau 3 Bilder hochgeladen werden
