### ISSUE TITLE
Datenbank aufräumen

### ISSUE THREAD

**Issue by daullmer** [Cryp-Tour/website#44]
Es sollten nur Touren existieren, für die auch ein TourToken auf der Blockchain existiert und eine GPX-Datei vorhanden ist.

Entweder wir löschen alle Touren für die das nicht der Fall ist, oder laden noch GPX-Dateien hoch und erstellen neue Tokens für diese Touren

**Comment by fabiankuffer** [comment]
Ich würde einfach alle Touren löschen, da wir glaub ich bis jetzt eh nur Testtouren erstellt haben.

[Hier gibts ein paar GPX-Dateien wofür wir Touren erstellen können.](https://github.com/gps-touring/sample-gpx)
